### PR TITLE
Un-deoptimization library edition

### PR DESCRIPTION
**Pull request by helpful-fox-senko-san**
Together with https://github.com/TexTools/FFXIV_TexTools_UI/pull/286

This reduces time on startup loading the item cache on EW database from 3s -> 1s

Model preview loading times are reduced around 3-5x.

Texture loading times are much faster too.

### CODE REVIEW

**Comment by helpful-fox-senko-san** [comment]
This will close #59

**Comment by Lunaretic** [comment]
Looks good.

**Comment by Squall-Leonhart** [comment]
This will break the viewer, the Helix Toolkit update requires reimplementing Culling

**Comment by Squall-Leonhart** [comment]
nvm, forgot the depth peeling wasn't in the framework

**Comment by helpful-fox-senko-san** [comment]
> This will break the viewer, the Helix Toolkit update requires reimplementing Culling

Backface culling toggle does work but this just reminded me that translucency is not working 🧀 I will try to remember where I need to re-add a line to fix that..........

(Edit: Oh you meant the other stuff but yeah I gotta fix translucency mode anyway)

**Comment by helpful-fox-senko-san** [comment]
Can confirm updating Helix Toolkit broke the Translucency toggle, so its possible it did break other translucency as well (I don't know any examples to check). I'm gonna look in to it and otherwise I guess recommend reverting the update.

**Comment by helpful-fox-senko-san** [comment]
```diff
--- a/FFXIV_TexTools/Views/Models/FullModelView.xaml
+++ b/FFXIV_TexTools/Views/Models/FullModelView.xaml
@@ -49 +49 @@
-                OITRenderMode="DepthPeeling" OITWeightMode="Linear0" ZoomDistanceLimitNear="0.0001">
+                OITRenderMode="SinglePassWeighted" ZoomDistanceLimitNear="0.0001">
diff --git a/FFXIV_TexTools/Views/Models/ModelView.xaml b/FFXIV_TexTools/Views/Models/ModelView.xaml
index d4392d9..eb22afe 100644
--- a/FFXIV_TexTools/Views/Models/ModelView.xaml
+++ b/FFXIV_TexTools/Views/Models/ModelView.xaml
@@ -54 +54 @@
-                OITRenderMode="DepthPeeling" OITWeightMode="Linear0" ZoomDistanceLimitNear="0.0001">
+                OITRenderMode="SinglePassWeighted" ZoomDistanceLimitNear="0.0001">
```
This appears to have been the correct mode to use :sob:

**Pull request merged**
